import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc-server/react";
import { cache } from "react";
import { headers } from "next/headers";
import { Toaster } from "sonner";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const getHeaders = cache(async () => headers());

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased`}
      >
        <TRPCReactProvider headersPromise={getHeaders()}>
          {children}
        </TRPCReactProvider>
        <Toaster richColors theme="system" />
      </body>
    </html>
  );
}
